1. Load Dataset 
2. Initial Data Inspection 
3. Missing Value Analysis 
4. Cancelled Order Analysis 
5. Invalid Transaction Analysis 
6. Duplicate Analysis 
7. Data Cleaning 
8. Feature Engineering 
9. Final Data Quality Report 
10. Export Cleaned Dataset

1. Load Dataset

In [1]:
import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)

# Load dataset
df = pd.read_csv("D:\ANURAG\Customer Retention + Cohort Analysis project\kaggle dataset.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully!
Shape: (541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

2. Initial Data Inspection

In [2]:
# Display basic information
print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nDataset Information:")
df.info()

print("\nFirst 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

Dataset Shape:
(541909, 8)

Column Names:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

Data Types:
InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

First 5 Rows:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

Last 5 Rows:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [3]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [4]:
df.describe(include="object")

,InvoiceNo,StockCode,Description,InvoiceDate,Country
count,541909,541909,540455,541909,541909
unique,25900,4070,4223,23260,38
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,10/31/2011 14:41,United Kingdom
freq,1114,2313,2369,1114,495478

3. Missing Value Analysis

In [5]:
# Check total missing values

missing_values = df.isnull().sum()

print("Missing Values:")
print(missing_values)

Missing Values:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [34]:
# Missing value percentage

missing_percentage = (
    df.isnull().sum() / len(df)
) * 100

missing_summary = pd.DataFrame({"Missing Values": missing_values, "Missing Percentage": missing_percentage })

missing_summary

             Missing Values  Missing Percentage
InvoiceNo                 0            0.000000
StockCode                 0            0.000000
Description            1454            0.268311
Quantity                  0            0.000000
InvoiceDate               0            0.000000
UnitPrice                 0            0.000000
CustomerID           135080           24.926694
Country                   0            0.000000

In [35]:
# Rows with missing CustomerID

missing_customer = df[df["CustomerID"].isnull()].copy()

print("Rows with missing CustomerID:")
print(missing_customer.shape)

missing_customer.head()

Rows with missing CustomerID:
(135080, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/2010 11:52,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,12/1/2010 14:32,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,12/1/2010 14:32,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,12/1/2010 14:32,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,12/1/2010 14:32,1.66,NaN,United Kingdom

In [36]:
# Rows with missing Description

missing_description = df[df["Description"].isnull()].copy()

print("Rows with missing Description:")
print(missing_description.shape)

missing_description.head()

Rows with missing Description:
(1454, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/2010 11:52,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,12/1/2010 14:32,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,12/1/2010 14:34,0.0,NaN,United Kingdom

4. Cancelled Order Analysis

In [9]:
# convert InvoiceNo to string.

df["InvoiceNo"] = df["InvoiceNo"].astype(str)

In [37]:
# Identify cancelled orders

cancelled_orders = df[df["InvoiceNo"].str.startswith("C")].copy()

print("Total Cancelled Transaction Rows:")
print(cancelled_orders.shape[0])

cancelled_orders.head()

Total Cancelled Transaction Rows:
9288

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,12/1/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom

In [38]:
# Number of unique cancelled invoices

print(
    "Unique Cancelled Orders:", cancelled_orders["InvoiceNo"].nunique())

Unique Cancelled Orders: 3836

In [39]:
# Total cancellation value

# Because cancelled transactions generally have negative quantities:

cancelled_orders["Revenue"] = (cancelled_orders["Quantity"] * cancelled_orders["UnitPrice"])

print("Total Cancelled Value:",cancelled_orders["Revenue"].sum())

Total Cancelled Value: -896812.49

In [40]:
print("Absolute Cancelled Value:",abs(cancelled_orders["Revenue"].sum()))

Absolute Cancelled Value: 896812.49

In [14]:
# Preview cancellation data

cancelled_orders[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,12/1/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,12/1/2010 10:24,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,12/1/2010 10:24,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,12/1/2010 12:38,4.25,17897.0,United Kingdom

5. Invalid Transaction Analysis

In [15]:
# Quantity less than or equal to zero

invalid_quantity = df[(~df["InvoiceNo"].str.startswith("C")) &(df["Quantity"] <= 0)].copy()

print("Invalid Quantity Rows:")
print(invalid_quantity.shape[0])

invalid_quantity.head()

Invalid Quantity Rows:
1336

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,12/1/2010 16:50,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,12/2/2010 14:42,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,12/3/2010 15:30,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,12/3/2010 15:30,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,12/3/2010 15:30,0.0,NaN,United Kingdom

In [16]:
# UnitPrice less than or equal to zero

invalid_price = df[
    (~df["InvoiceNo"].str.startswith("C")) &
    (df["UnitPrice"] <= 0)
].copy()

print("Invalid Price Rows:")
print(invalid_price.shape[0])

invalid_price.head()

Invalid Price Rows:
2517

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/2010 11:52,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,12/1/2010 14:32,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,12/1/2010 14:34,0.0,NaN,United Kingdom

6. Duplicate Analysis

In [18]:
# Check exact duplicate rows

duplicate_count = df.duplicated().sum()

print("Total Exact Duplicate Rows:")
print(duplicate_count)

Total Exact Duplicate Rows:
5268

In [19]:
# Display duplicate rows

duplicates = df[
    df.duplicated()
].copy()

duplicates.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,12/1/2010 11:45,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,12/1/2010 11:45,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,12/1/2010 11:45,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,12/1/2010 11:45,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,12/1/2010 11:49,2.95,17920.0,United Kingdom

In [33]:
# Percentage of duplicates

duplicate_percentage = ( df.duplicated().sum() / len(df)) * 100

print( f"Duplicate Percentage: {duplicate_percentage:.2f}%" )

Duplicate Percentage: 0.97%

7. Data Cleaning

In [41]:
# Remove cancelled orders

sales_df = df[~df["InvoiceNo"].str.startswith("C")].copy()

print("After removing cancelled orders:")
print(sales_df.shape)

After removing cancelled orders:
(532621, 8)

In [22]:
sales_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [42]:
# Separate missing CustomerID

missing_customer = sales_df[sales_df["CustomerID"].isnull()].copy()

print("Rows with missing CustomerID:",missing_customer.shape[0])

Rows with missing CustomerID: 134697

In [43]:
# Remove them from the main dataset:

sales_df = sales_df.dropna(subset=["CustomerID"]).copy()

print("Shape after removing missing CustomerID:",sales_df.shape)

Shape after removing missing CustomerID: (397924, 8)

In [44]:
# Separate invalid UnitPrice

invalid_price = sales_df[sales_df["UnitPrice"] <= 0].copy()

print("Invalid UnitPrice Rows:",invalid_price.shape[0])

sales_df = sales_df[sales_df["UnitPrice"] > 0].copy()

sales_df.shape

Invalid UnitPrice Rows: 40

(397884, 8)

In [54]:
# Remove duplicates

before_duplicates = sales_df.shape[0]

sales_df = sales_df.drop_duplicates().copy()

after_duplicates = sales_df.shape[0]

print("Duplicates Removed:",before_duplicates - after_duplicates)

Duplicates Removed: 5192

In [45]:
# Handle missing Description


print("Missing Description:",sales_df["Description"].isnull().sum())

# want to remove them:

# sales_df = sales_df.dropna(subset=["Description"])

Missing Description: 0

In [46]:
# Fix data types

sales_df["InvoiceDate"] = pd.to_datetime(sales_df["InvoiceDate"])

sales_df["CustomerID"] = (sales_df["CustomerID"].astype(int))

sales_df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int64
Country                object
dtype: object

8. Feature Engineering

In [48]:
# Revenue

sales_df["Revenue"] = (sales_df["Quantity"] * sales_df["UnitPrice"])

In [49]:
# Invoice Date Features

# Year
sales_df["Year"] = (sales_df["InvoiceDate"].dt.year)

# Month Number
sales_df["Month"] = (sales_df["InvoiceDate"].dt.month)

# Month Name
sales_df["Month_Name"] = (sales_df["InvoiceDate"].dt.month_name())

# Year-Month
# This will be extremely useful for cohort analysis.

sales_df["Year_Month"] = (sales_df["InvoiceDate"].dt.to_period("M").astype(str))

# Day of Week
sales_df["Day_Name"] = (sales_df["InvoiceDate"].dt.day_name())

# Day of Month
sales_df["Day"] = (sales_df["InvoiceDate"].dt.day)

# Hour
# This can help analyze purchasing behavior by time.
sales_df["Hour"] = (sales_df["InvoiceDate"].dt.hour)

Final Data Quality Report Of SALES DATA

Now check whether the cleaned data has the issues we intended to remove.

In [57]:
print("=" * 50)
print("FINAL DATA QUALITY REPORT")
print("=" * 50)

print("\nFinal Dataset Shape:")
print(sales_df.shape)

print("\nMissing Values:")
print(sales_df.isnull().sum())

print("\nExact Duplicate Rows:")
print(sales_df.duplicated().sum())

print("\nCancelled Orders:")
print(sales_df["InvoiceNo"].str.startswith("C").sum())

print("\nQuantity <= 0:")
print((sales_df["Quantity"] <= 0).sum())

print("\nUnitPrice <= 0:")
print((sales_df["UnitPrice"] <= 0).sum())

print("\nCustomerID Missing:")
print(sales_df["CustomerID"].isnull().sum())

print("\nTotal Revenue:")
print(f"£{sales_df['Revenue'].sum():,.2f}")

print("\nUnique Customers:")
print(sales_df["CustomerID"].nunique())

print("\nUnique Orders:")
print(sales_df["InvoiceNo"].nunique())

print("=" * 50)
print("DATA CLEANING COMPLETED")
print("=" * 50)

==================================================
FINAL DATA QUALITY REPORT
==================================================

Final Dataset Shape:
(392692, 16)

Missing Values:
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
Revenue        0
Year           0
Month          0
Month_Name     0
Year_Month     0
Day_Name       0
Day            0
Hour           0
dtype: int64

Exact Duplicate Rows:
0

Cancelled Orders:
0

Quantity <= 0:
0

UnitPrice <= 0:
0

CustomerID Missing:
0

Total Revenue:
£8,887,208.89

Unique Customers:
4338

Unique Orders:
18532
==================================================
DATA CLEANING COMPLETED
==================================================

Professional summary table:

In [56]:
quality_report = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Missing CustomerID",
        "Duplicate Rows",
        "Quantity <= 0",
        "UnitPrice <= 0",
        "Cancelled Orders",
        "Unique Customers",
        "Unique Orders"
    ],
    
    "Value": [
        sales_df.shape[0],
        sales_df.shape[1],
        sales_df["CustomerID"].isnull().sum(),
        sales_df.duplicated().sum(),
        (sales_df["Quantity"] <= 0).sum(),
        (sales_df["UnitPrice"] <= 0).sum(),
        sales_df["InvoiceNo"].str.startswith("C").sum(),
        sales_df["CustomerID"].nunique(),
        sales_df["InvoiceNo"].nunique()
    ]
})

quality_report

               Metric   Value
0          Total Rows  392692
1       Total Columns      16
2  Missing CustomerID       0
3      Duplicate Rows       0
4       Quantity <= 0       0
5      UnitPrice <= 0       0
6    Cancelled Orders       0
7    Unique Customers    4338
8       Unique Orders   18532

10. Export Cleaned Dataset

In [59]:
# Export main cleaned dataset

sales_df.to_csv("online_retail_cleaned.csv",index=False)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!

In [60]:
cancelled_orders.to_csv("cancelled_orders.csv",index=False)

missing_customer.to_csv("missing_customer_id.csv",index=False)

invalid_quantity.to_csv("invalid_quantity.csv",index=False)

invalid_price.to_csv("invalid_price.csv",index=False)

print("All datasets exported successfully!")

All datasets exported successfully!

Cleaning summary that tracks how many rows are removed at every stage:

In [61]:
print("Original Rows:", len(df))
print("Final Cleaned Rows:", len(sales_df))
print("Rows Removed:", len(df) - len(sales_df))
print("Percentage Removed:",round((len(df) - len(sales_df)) / len(df) * 100, 2),"%")

Original Rows: 541909
Final Cleaned Rows: 392692
Rows Removed: 149217
Percentage Removed: 27.54 %

In [ ]:
# from sqlalchemy import create_engine

# # MySQL connection
# username = "root"
# password = "683456k"
# host = "localhost"
# port = "3306"
# database = "online_retail_analysis"

# engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# # Write DataFrame to MySQL
# table_name = "online_retail"   # choose any table name
# df.to_sql(table_name, engine, if_exists="replace", index=False)

# # Read back sample
# pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

In [1]:
pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in c:\users\anura\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in c:\users\anura\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\anura\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\anura\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anura\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\anura\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anura\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in c:\users\anura\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\anura\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\anura\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from sqlalchemy import create_engine

# MySQL connection details
username = "root"
password = "683456k"
host = "localhost"
port = 3306
database = "online_retail_analysis"

# # CSV file path
# csv_file = "online_retail_cleaned.csv"

# Read CSV
df1 = pd.read_csv(r"D:\ANURAG\Customer Retention + Cohort Analysis project\online_retail_cleaned.csv")

# Create MySQL connection
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Load data into MySQL
df1.to_sql("online_retail",engine,if_exists="replace", index=False)


print("CSV data loaded successfully!")

NameError: name 'pd' is not defined